server:
  port: 8180
spring:
  application:
    name: spring-batch-template
  datasource:
    url: jdbc:h2:mem:batch-test
    username: sa
    password: 1q2w3e4r
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none # Hibernate 가 테이블 스키마를 변경하지 않도록 설정
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  batch:
    job:
      enabled: false # true 이면 애플리케이션 실행 시 Job 자동 실행
  logging:
    level:
      org.springframework.batch: DEBUG  # Spring Batch 관련 로그 레벨을 DEBUG로 설정
      org.hibernate.SQL: DEBUG  # SQL 쿼리 로그를 확인
      org.springframework.jdbc: DEBUG  # JDBC 관련 로그 확인
